### ISSUE TITLE
Neow Bonus to gain gold crashing Game as Non-Wanderer character

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#101]
Weird bug- picking the "Gain 100 gold" whale bonus is actually crashing to desktop for me on Ironclad run.

My exact series of events was Picking Ironclad -> Pick whale bonus "100 gold" -> crash

**Comment by dbjorge** [comment]
Probably the hook for charity to track gold changes in MemoryHooksPatch is missing a null check when trying to access the player's MemoryManager

**Comment by mderb4** [comment]
Gonna try and take a look into this one.

**Comment by mderb4** [comment]
Ok I see the missing null check, took me longer to get everything set up though so testing will have to wait until tomorrow/Friday depending on when I get home from work tomorrow. After I verify that fixes it I'll open up the pull request.

**Comment by Frenoss** [comment]
That sounds great! Thanks for looking into it.

________________________________
