### ISSUE TITLE
Chain Lightning damage

### ISSUE THREAD

**Issue by Akkarin2304** [dbjorge/jorbs-spire-mod#104]
Chain Lightning seems to only deal half damage to other enemies after targeting Byrd in a fight.

**Comment by wang429** [comment]
Confirmed, in the Chosen_and_Byrds fight, Chain Lightning deals 3 damage to the Byrd, but only 5 to the Chosen when 9 is expected (base of 7 + 2). Example of similar correct behavior would be Sword Boomerang.

**Comment by wang429** [comment]
When testing this, also noticed that Chain Lightning damage from Chosen to Byrd isn't being reduced when hitting the Byrd. Chosen takes 7, then Byrd is 9. Similarly, 3_Byrds fight has Byrds taking 3 -> 5 -> 7 rather than 3->4->5. Upgraded version has similar issue.

**Comment by dbjorge** [comment]
The issue is going to be that it's calculating the card damage like a single target attack, where it should actually be calculating as if it were a multi damage attack first and then do the random order/+2s on top of the normal multi damage calculation

**Comment by stevematney** [comment]
I have some familiarity with this card. I could tackle this bug.

**Comment by dbjorge** [comment]
@stevematney go for it! If you aren't already familiar with the multi damage card mechanics, take a look at how fireball interacts with DamageAllEnemiesAction; I think that's probably the "correct" way to calculate the base damage per enemy. When testing, it would be good to try out different combinations of vulnerable/weak/intangible/banished on enemies in addition to the bird half damage; you can use the dev console `power Vulnerable 1` command to speed that up

**Comment by stevematney** [comment]
Awesome. That's very helpful. Thanks!
