### ISSUE TITLE
Wrath doesn't stack with Ritual Dagger

### ISSUE THREAD

**Issue by Frenoss** [dbjorge/jorbs-spire-mod#109]
The damage upgrade from Wrath needs to, but doesn't, stack with the upgrading damage from Ritual Dagger. The solution in this particular instance is to use the misc field.

I don't think we can generically solve this for other mod's cards that don't track permanent damage additions on their own. Perhaps we can work better with them through the misc field. Note that misc is also tracked by Bottled Flame and used when recreating decks (in the CardLibrary.getCopy method).

**Comment by dbjorge** [comment]
I agree that there's probably not a way to solve this for all possible future cards that override `baseDamage` at random points. There are other cards that use `misc` for non-damage purposes, so I'd prefer to avoid touching it with Wrath; I think I would lean towards special casing Ritual Dagger
