### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#138]
* [ ] Wrath upgrade counts: would have been helpful for quickly testing some cases with Scorching Ray
* [ ] Block add/remove: surprised it doesn't already exist.
* [x] Power: Burning and other new powers should be usable.

**Comment by dbjorge** [comment]
c1a618a implements `power stsjorbsmod:BurningPower 1` (and all other powers the mod adds)

**Comment by dbjorge** [comment]
4e57ba97 implements `wrath` and `block`
