### ISSUE TITLE
Give Wrath metaupgrades different FX

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#139]
With Pride and Wrath together, it can be a bit confusing as to which memory upgraded which card.

**Comment by Frenoss** [comment]
Also good to consider better interaction with Bottled Flame.
![image](https://user-images.githubusercontent.com/6187622/68845347-1e2bf800-0680-11ea-9d37-6849b544ebab.png)

**Comment by wang429** [comment]
going to separate out the relocation of the wrath icon.

**Comment by wang429** [comment]
Addressed by #227
