### ISSUE TITLE
ExhumeCardsAction should move card(s) to discard if hand is full

### ISSUE THREAD

**Issue by ImprovPanda** [dbjorge/jorbs-spire-mod#140]
How do you add labels?

**Comment by wang429** [comment]
I think it's by being a collaborator.

Re: Issue, need to determine what expected behavior should be.

**Comment by ImprovPanda** [comment]
I just figure it would enter draw or discard pile in this case case

**Comment by dbjorge** [comment]
Consensus on discord was the Exhume action should go to discard if no room in hand, similar to endless agony. Should just be an update to `ExhumeCardsAction`

**Comment by dbjorge** [comment]
fixed by 2739c3e
