### ISSUE TITLE
Finding "Divine Fountain" event b/c of Grimoire

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#151]
Divine Fountain event is to remove all curses from deck, which is triggered by having >= 1 curses in deck (excluding Ascender's Bane). Grimoire proc's this event by being a curse (even though unremovable).

Following through with the "Remove all curses" event does not actually remove Grimoire though.

**Comment by Frenoss** [comment]
Thanks for reporting this issue. Do you know if you encountered it on version 0.37.0 or an earlier version?

**Comment by johnplunk** [comment]
Found it 0.37!

**Comment by Frenoss** [comment]
Good deal. The next version should have a fix. Thanks!

**Comment by dbjorge** [comment]
fixed by #157
