### ISSUE TITLE
Chastity is not removing dex. if forgotten

### ISSUE THREAD

**Issue by ImprovPanda** [dbjorge/jorbs-spire-mod#152]
Eye of the storm into chastity gave the normal +2 dex but then when I used scorching ray afterward dex remained for the rest of the fight. 

on an unrelated note Lagavulin is much easier when you have an extra 6 dex lol

**Comment by dbjorge** [comment]
This is by design; Chastity is intended to give permanent dex if you can find a way to forget it immediately (it loses 1 dex per turn if you don't have a means to forget it)
