### ISSUE TITLE
Grimoire making all Material Components cost 0

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#153]
Quicksilver/Stone both cost 1 in normal play, but cost 0 energy when made by Grimoire.

Confirmed by Jorbs that Grimoire should be giving the Material Components as their original energy costs.

**Comment by Frenoss** [comment]
Nice find! We let the player choose a card via the DiscoveryAction, which sets the cost to 0 for the current turn. This action is re-used from the Attack, Power, and Skill potions.
