### ISSUE TITLE
Dead Branch activates on Entombed effect

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#154]
Currently, when Grimoire exhausts at the start of combat to start in the exhaust pile, Dead Branch will activate and give you a card in your opening hand. Unsure if this is intended? 

I assume this is an Entombed effect, not a Grimoire only problem

**Comment by dbjorge** [comment]
Yes, definitely a bug. Yes, related to Entombed, not grimoire specifically.
