### ISSUE TITLE
My True Form mod starts with two of each of the main game's forms

### ISSUE THREAD

**Issue by Frenoss** [dbjorge/jorbs-spire-mod#156]
This feels like a bug in the frameworks we're using and not ours, since only one of Arcane Form is added.

**Comment by dbjorge** [comment]
I agree, it would make more sense to add this as a patch in BaseMod based on the `BaseModCardTags.FORM` tag

**Comment by dbjorge** [comment]
Tracking as https://github.com/daviscook477/BaseMod/issues/235
