### ISSUE TITLE
True Strike not affected by Strike Dummy

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#165]
True Strike does not respect Strike Dummy buff. 

Probably something to do with the "lose hp" workaround that it does?

**Comment by dbjorge** [comment]
This is probably 2 different issues; I think it's probably missing the STRIKE card tag it ought to have, but also it probably wouldn't work right anyway until #54 is fixed. Thanks for calling it out, I'd forgotten about the first part!

**Comment by dbjorge** [comment]
Fixed the strike tagging, converging other true strike issues into #54
