### ISSUE TITLE
Greed kills do not have a gold animation / jingle

### ISSUE THREAD

**Issue by squid-lee** [dbjorge/jorbs-spire-mod#166]
Killing a mob when you have greed active does not give any feedback besides the number ticking up silently (unlike other gold granting cards)

**Comment by dbjorge** [comment]
![greed_gold_effect_166](https://user-images.githubusercontent.com/376284/69014219-dd143c00-093c-11ea-85a1-eb7f7f14eebc.gif)

fixed by 71d639b
