### ISSUE TITLE
Arcane Weapon: tooltip and stacking behavior are incorrect

### ISSUE THREAD

**Issue by squid-lee** [dbjorge/jorbs-spire-mod#167]
Arcane weapon appears to (deliberately?) take its permanent value based on buffs / debuffs when played.
A few examples:
it has 4 dmg base, but ought to do 5 damage per turn if you have 1str when played
it has 4 dmg base, but ought to do 3 damage per turn if you have weak when played
These both seemed to work even when the strength / weak disappeared?

I got an Akabeko, and played Arcane Weapon+ while the Akabeko was still granting +8.
The tooltip & power icon said 'do 14 damage', but the power only did 14 damage on the first strike, and 6 on the second turn. 

So the question is - at what point does Arcane Weapon decide how much damage it ought to do?
And when does the tooltip lock itself in?

**Comment by squid-lee** [comment]
After looking at this again, 'Arcane Weapon's actual damage is based on the current buffs, it's just that the tooltip is wrong.

**Comment by dbjorge** [comment]
Secondary related issue: report on discord suggests that Arcane Weapon's self-stacking behavior is off (updating tooltip/rendered amount but not actual damage), update should also include fixing that.

**Comment by dbjorge** [comment]
Fixed by 89818e4
