### ISSUE TITLE
Remembering a new memory when lust is clarified & remembered still grants 2 weak

### ISSUE THREAD

**Issue by squid-lee** [dbjorge/jorbs-spire-mod#168]
Lust was remembered.
I use eye of the storm, clarifying Lust, and remembering Chastity.
I got two weak.

The starter relic specifically says 'Memories you have Clarify of won't be forgotten when remembering a new memory'

**Comment by dbjorge** [comment]
The mechanics here are by design, but the keyword text for clarity you've pointed out is outdated/misleading. We should correct it to something more like "While you have Clarity of a memory, you keep its passive effect even after forgetting the memory"
