### ISSUE TITLE
What if Rot exhausts?

### ISSUE THREAD

**Issue by ImprovPanda** [dbjorge/jorbs-spire-mod#184]
I think Rot is too strong a curse if it doesn't exhaust out of hand if played. simply because it duplicates and makes book of tongues a much worse card in general.

**Comment by dbjorge** [comment]
Per https://clips.twitch.tv/HedonisticPlayfulBibimbapWOOP, making this Ephemeral

**Comment by dbjorge** [comment]
Fixed by 6556b7e
