### ISSUE TITLE
Game softlock when playing ray of frost and inferno+ in Time Eater Fight.

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#186]
From DaukashToday:

> I used Inferno+ as the last card in Time Eater's 12 card cycle right after using ray of frost(while the RoF strike animation was still going) and the game locked up. Just thought you might want to know.

https://discordapp.com/channels/329758756076519436/638464764863053851/646061937112907786

**Comment by wang429** [comment]
Per Daukash#0001
> Sorry for the late response, was turn 4 of combat, I playing index into scorching ray, the common card that causes 9 burning, frost ray, then soft-locked on playing inferno. Too many relics to remember(Fusion Hammer first boss relic into shovel from a ?), thorns, strength for gold, and the other one right next to those 2 clarified, lust clarified and remembered. I had pyromancy and Mirror shield powers running....

**Comment by dbjorge** [comment]
After further discussion in discord and attempts to repro, we think this is probably the same as #187 . Will reopen if the issue comes up again.
