### ISSUE TITLE
Wrath's interactions with copied cards

### ISSUE THREAD

**Issue by zintertainment** [dbjorge/jorbs-spire-mod#192]
I had clarity of wrath and killed a non-minion enemy (red lous) with Mindworm, but Mindworm did not retain the damage upgrade in the next combat. It is suspected this is because the kill was done with a copy of Mindworm, rather than the original.

**Comment by wang429** [comment]
From Discord user Zint#3582

**Comment by dbjorge** [comment]
This is the intended behavior.
