### ISSUE TITLE
Mirror image appears inside some minions

### ISSUE THREAD

**Issue by ImprovPanda** [dbjorge/jorbs-spire-mod#209]
**Version**
Slay the spire: main
Mod version: 47
**Describe the bug**
mirror image sprite appears inside minions for the awakened one and i would imagine some others but have not reproduced
**To Reproduce**
1. play magic mirror while in combat with multiple foes
2. magic mirror appears inside some minions
3. observe

**Expected behavior**
Magic mirror to appear perhaps behind the wanderer

**Screenshots**
![mirror bug](https://user-images.githubusercontent.com/57649534/69780895-3157c100-1172-11ea-923c-2cd1b6d25a63.png)

**Additional context**

**Comment by dbjorge** [comment]
Fixed by 7496f0a
