### ISSUE TITLE
Cards with dynamically calculated damage/block/etc should use dynamic card desc like Blizzard

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#211]
(extracted from #83)

Magic Missiles, Snake Oil, and all other cards that calculate damage/block/etc dynamically should use `Blizzard` as their template for how to display the dynamically calculated effects:

* Have the base card description include *only* the description of the calculation (eg, "Gain 1 Block per Clarity you have."
* Have `applyPowers` and `calculateCardDamage` dynamically update the description to append the total ("(Gain !B Block.)"), and have `onMoveToDiscard` reset it

Text example from Blizzard:

```json
  "Blizzard": {
    "NAME": "Blizzard",
    "DESCRIPTION": "Deal damage equal to !M! times the number of Frost Channeled this combat to ALL enemies.",
    "UPGRADE_DESCRIPTION": "",
    "EXTENDED_DESCRIPTION": [
      " NL (Deals !D! damage.)",
      ""
    ]
  },
```

**Comment by 4812622** [comment]
Blizzard also doesn't display how much damage it does when it's in deck or discard instead of your hand, which is a problem.

**Comment by dbjorge** [comment]
* [x] Mania: #219
* [x] Magic Missiles: #219
* [x] Animate Objects #219
* [x] Mending: c27d5b1
* [x] Prepare: 4f609e0
* [x] Misty Step: 57f4b40
* [x] Firebolt: 5dd71d3
* [x] Hurt: 64a1f3a

**Comment by dbjorge** [comment]
I think that's all of them currently in the game! If anyone finds others that ought to use dynamic text but aren't, feel free to open new/individual bugs for them
