### ISSUE TITLE
Playing Forbidden Grimoire with Blue Candle costs 1 HP

### ISSUE THREAD

**Issue by sanity-dance** [dbjorge/jorbs-spire-mod#213]
**Version**
Slay the spire: BETA
Mod version: v0.47.2

**Describe the bug**
Playing the Forbidden Grimoire on Wanderer proccs Blue Candle and costs 1 HP.

**To Reproduce**
1. Have Blue Candle.
2. Play the Forbidden Grimoire.

**Expected behavior**
I expected this to not cost me HP.

**Comment by dbjorge** [comment]
Obsoleted by bcc9415 (makes Grimoire not be a curse)
