### ISSUE TITLE
Burning and Block interaction deceptive

### ISSUE THREAD

**Issue by 4812622** [dbjorge/jorbs-spire-mod#217]
Burning is visible on the health bar of the enemy in the same way that Poison is.  I expect Burning to ignore Block and take that visible chunk of the enemy health.  It doesn't work like that in practice - it IS affected by Block.  

It should probably only show that chunk of the HP bar after taking into account Block - like if an enemy has 10 Block, 20 HP, and 15 Burning, the HP bar would show as 75% red and 25% orange, rather than 25% red and 75% orange, as it is currently.

**Comment by dbjorge** [comment]
This sounds reasonable to me!

**Comment by dbjorge** [comment]
Fixed by #224
