### ISSUE TITLE
Hold Monster and Artifact

### ISSUE THREAD

**Issue by 4812622** [dbjorge/jorbs-spire-mod#218]
The -3 STR from Kindness and the Str down from Hold Monster itself are both negated by a single Artifact charge.

**Comment by wang429** [comment]
Having trouble reproducing this. Is it possible that you were already in kindness?

**Comment by wang429** [comment]
or maybe clarity of kindness?

**Comment by dbjorge** [comment]
Some interactions related to this combination were fixed by #224 and 9e007f2, and I agree that I can't repro any further bad interaction as exactly described by this. Give it a try in v0.49.0 with those 2 fixes and feel free to re-open if you're still able to reproduce a problem in that version!
