### ISSUE TITLE
Wrath upgraded Barb

### ISSUE THREAD

**Issue by 4812622** [dbjorge/jorbs-spire-mod#222]
Slay the Spire: Beta
Version: 4.8.0

While remembering Wrath, I played an attack that was in my deck, then Barb, then Snake Oil to end the fight.  Instead of boosting the first attack, it boosted Barb, which then disappeared because it wasn't in my deck.

**Comment by dbjorge** [comment]
This is as-designed; it's intentional that you need to give thought to card ordering to capitalize on Wrath.
