### ISSUE TITLE
Flame Ward not applying to all enemies

### ISSUE THREAD

**Issue by 4812622** [dbjorge/jorbs-spire-mod#223]
**Version**
Slay the spire: Beta
Version: 4.8.0

I played Flame Barrier against Bronze Automaton.  The minion shot me, but the boss and the other minion didn't receive Burning.  The boss, at least, definitely didn't have Artifact on it, because I played the card that applies Weak 3 times.

**Comment by dbjorge** [comment]
Flame Ward applies burning to all **attackers** (ie, enemies which are currently intending to attack), not all enemies. I wasn't able to reproduce this for cases where the enemies in question were attacking, so I'm assuming that misunderstanding is what led to this bug; if you are able to reproduce it with enemies that are intending to attack, feel free to comment/reopen!
