### ISSUE TITLE
20191208-20191209 balance changes

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#230]
> balance pass from tonight:
> - [ ] burning 50% falloff -> 33% falloff
> - [ ] burning prevents all healing
>
> functionality changes:
> - [ ] make burning prevent heal on time eater/champ even though they cleanse
> - [x] make cards which exhume when snap at end of turn 7 go into starting hand for turn 8

**Comment by wang429** [comment]
Implementation notes, ideally move snap after turn end card discard. If that can't work, maybe have fragile mind's snap trigger exhume at start of enemy turn?

**Comment by wang429** [comment]
The exhume on snap is its own ticket #228

**Comment by dbjorge** [comment]
Burning updates resolved by #233, rest moved to separate issue
