### ISSUE TITLE
2019-12-12 stream changes

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#234]
List of things put in the `#wanderer-feedback` channel during the 2019-12-12 stream.
- [ ] flame ward should get reworked to deal some damage immediately, makes for more interactivity. Something like deal 10 damage then apply 6 burning
- [ ] mirror image: the attack animation is shown hitting big me instead of little me
- [ ] smoke bomb: he takes the memories with him, should probably leave them as a static interface like defect does
- [x] mirror image: dying minion procs gremlin horn
- [ ] burning: UI element that shows shield on fire if an enemy has block
- [ ] mirror image: suggestion for stacking: give intangible and each stack adds one hp
- [ ] mirror image: minime faces wrong way in a4 elite fight when only shield is left
- [ ] mirror image: dies to beat of death
- [x] scorching ray's beam hitbox is up in the sky in the act 4 elite fight.
- [x] seems like an attack hitting the mirror image triggers burning ward, is that desireable?

**Comment by dbjorge** [comment]
Scorching ray hitbox fixed by 9379cd8

**Comment by dbjorge** [comment]
Mirror image + gremlin horn fixed by 5ea4f95

**Comment by wang429** [comment]
burning ward triggering when an attack hits mirror image is fine.

**Comment by wang429** [comment]
Splitting this out into a few issues:
Flame ward: #240 
Mirror Image: #241 
Smoke Bomb: #242 
Burning: #243
