### ISSUE TITLE
Flame ward should deal burning immediately

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#240]
flame ward should get reworked to deal some damage immediately, makes for more interactivity. Something like deal 10 damage then apply 6 burning

**Comment by dbjorge** [comment]
Closing for now per jorbs:

> 5:43 PM] brosmike: You mentioned wanting Flame Ward to update to do a mix of immediate damage + burning rather than just burning, right? Did you have specific numbers in mind?
> [5:43 PM] brosmike: Also, you mentioned the "only applying to enemies with attack intents" thing feeling awkward, did you want to change that?
> [5:54 PM] jorbs: templating is probably the issue with having it deal damage immediately too
> [5:54 PM] jorbs: i'm okay with it being like it is for now
