### ISSUE TITLE
Mirror Image change requests

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#241]
- [x] the attack animation is shown hitting big me instead of little me
- [x] suggestion for stacking: give intangible and each stack adds one hp
- [ ] minime faces wrong way in a4 elite fight when only shield is left
- [x] mirror image: dies to beat of death

**Comment by dbjorge** [comment]
intangible + hp suggestion implemented in 5aab200

**Comment by dbjorge** [comment]
facing in shield+spear fight fixed by 95a8f20
