### ISSUE TITLE
burning: UI element that shows shield on fire if an enemy has block

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#243]
Provide more clarity to Burning when owner has burning and block. Maybe set the shield on fire or a partial bar on the shield.

**Comment by Cartopol** [comment]
Since merging the burning block icon, the block icon is always burning, even if block's owner is not burning. Presumably the RenderBurningBlockPatch needs to include a check on having BurningPower before rendering the block icon.
