### ISSUE TITLE
Banish: missing interactions

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#251]
* [x] Spheric Guardian still gains strength while banished
* [x] Arcane Weapon should avoid targetting banished enemies
* [x] Awakened One should not gain strength when player uses powers if banished
* [x] Gremlin Nob still gains strength when playing skills if banished
* [x] Timer on Exploders still goes up when banished (will need special handling for them, probably)

**Comment by wang429** [comment]
Beat of Death? Should this just be all powers don't tick?
If Arcane Weapon doesn't random into the banished enemy, what about Chain Lightning? What about somehow getting Rip and Tear or just getting lightning orbs?

**Comment by wang429** [comment]
Arcane Weapon seems to have been handled previously. I vaguely remember it happening, but I also don't.
