### ISSUE TITLE
Death Throes doesn't proc on Darklings

### ISSUE THREAD

**Issue by Erichilles** [dbjorge/jorbs-spire-mod#252]
**Version**
Slay the spire: BETA
Mod version: 0.52.0

**Describe the bug**
Killed the first Darkling in the act 3 hallway fight, Gremlin horn proc'd but Death Throes didn't.

Not sure if this is intentional or not since of course things like Feed or Hand of Greed only work on final Darkling kill, but since Gremlin Horn proc'd, I figured it was worth mentioning since they both have the same wording.

Gremlin Horn: Whenever an enemy dies, gain energy and draw 1 card
Death Throes: Exhume whenever an enemy dies.

**To Reproduce**
1. Enter combat with Darkling and Death Throes in deck
2. Kill a darkling (without ending the fight)
3. Death Throes will not be exhumed.

**Expected behavior**
Unclear whether this is intended or not since there isn't really consistent behavior for these.

**Comment by dbjorge** [comment]
Current behavior is intended (see #60) , but thanks for checking!
