### ISSUE TITLE
Purge Mind doesn't clear actions if Gremlin Leader is killed but not the minions.

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#269]
Version 0.53.0
Found by Discord user Erichilles#8909 

Purge Mind will still cause Wanderer to snap if it kills Gremlin Leader or Reptomancer. I imagine the same happens against Collector too.

Expected: Purge Mind causes Wanderer to snap with killing the non-minion monster in a room of minions.
Actual: fight ends without snapping.

**Comment by dbjorge** [comment]
Fixed by #270
