### ISSUE TITLE
CULL: Waking Dream card description does not say it exhausts

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#296]
**Version**
Slay the spire: Beta
Mod version: 0.55.0

**Describe the bug**
Pretty simple- card exhausts but the wording on the card says it doesn't. Just throw the keyword in real quick. Google Sheet overview says the card should be exhausting, so the implementation is correct.

**To Reproduce**
1. Play Waking Dream
2. See that it exhausts
3. say "yep, that card sure did exhaust"

**Expected behavior**
I would expect the card that does not say exhaust to not exhaust, however the card does. The card is correct and my eyes are wrong but if we're being real technical here, my eyes are correct as the card says it shouldn't exhaust but then it does. Really, the only problem here is the card is exhausting, but since we know better that the card should exhaust, we can say with certainty that my eyes are in the wrong here and that the card is correct for exhausting when it is exhausting on my screen.

**Screenshots**
![temp](https://user-images.githubusercontent.com/47401869/71608059-d6840180-2b43-11ea-99f1-9c59c2fb21d3.PNG)

**Additional context**

**Comment by dbjorge** [comment]
Thanks, fixed by 7ec9b641
