### ISSUE TITLE
CULL: Rebuke damage description not updating

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#297]
**Version**
Slay the spire: Beta
Mod version: 0.55.0

**Describe the bug**
Rebuke is affected by Wrath stacks, but the base damage number does not update with the Wrath stacks.

**To Reproduce**
1. Kill enemy with Rebuke
2. Go into new fight with Wrath-buffed Rebuke
3. See that it does 11 damage, but the card's base damage total is still 10.

**Expected behavior**
Would expect the base damage number to be increasing with Wrath stacks.

**Screenshots**
![temp](https://user-images.githubusercontent.com/47401869/71608194-f1a34100-2b44-11ea-9959-a528b5fbb2c4.PNG)

**Additional context**
I have mutagenic strength in this screenshot so it shows it doing 17 damage, but in reality the base damage of the card is 14.

**Comment by dbjorge** [comment]
Fixed by de2129cc
