### ISSUE TITLE
Ivory Tower interaction with Necronomicurse

### ISSUE THREAD

**Issue by Frenoss** [dbjorge/jorbs-spire-mod#30]
Currently "Ivory Tower" exhausts a Necronomicurse card and a new one pops back into your hand. The old one is in the exhaust pile. This should change, but I'm not sure which way to go with it.

Should the behavior be not to exhaust it in the first place, or to actually escape the Necronomicurse for this fight and not have a new one return to your hand?

**Comment by dbjorge** [comment]
I would expect it to interact the same as any other card with an "exhaust other card(s)" effect. What happens if you Recycle a Necronomicurse?

**Comment by Frenoss** [comment]
Ohh, good point. This is the same interaction, then.
