### ISSUE TITLE
Enemies lose their Block before damage from Burning is applied

### ISSUE THREAD

**Issue by Cartopol** [dbjorge/jorbs-spire-mod#307]
When an enemy with BurningPower has any block, their block is lost before damage from Burning is applied. This means that Burning damage is only reduced by block when fighting a Sphere Guardian. 

Steps to reproduce:
1. Fight Lagavuling
2. Create Burning Flask
3. Play Burning Flask on Lagavulin while it has Metalicize
4. End turn

Expected result: Lagavulin blocks for 8, takes 6 damage from Burning and has 2 block remaining.
Actual result: Lagavulin loses all block, takes 6 damage from Burning and wakes up.

**Comment by wang429** [comment]
addressed by #321
