### ISSUE TITLE
CULL's Manifest is reset to 0 after save/reload

### ISSUE THREAD

**Issue by Cartopol** [dbjorge/jorbs-spire-mod#308]
When you save/reload with CULL while not in a room, your Manifest amount is 'reset to 0'.  If you needed to skip any number of floors when you Save & Quit, after Continue you no longer skip those floors. 

Steps to reproduce:
1. Start a run as CULL and enter first floor
2. End Turn 3 times
3. Win fight and skip rewards
(at this point, you are in the Map screen and can see that you need to skip 3 floors)
4. Go to Menu -> Save & Quit
5. Continue run

Expected result:
At the map screen, you should get a choice of Floor 5 rooms, as before Save & Quit

Actual result:
At the map screen, you get a choice of Floor 2 rooms, as if your Manifest is 0.

**Comment by dbjorge** [comment]
Fixed by fdf28bbd
