### ISSUE TITLE
Consuming a status card gives +3 maxHP instead of nothing

### ISSUE THREAD

**Issue by Cartopol** [dbjorge/jorbs-spire-mod#322]
When you consume a status card (e.g. with Cull's Splinter Soul), you gain +3 maxHP, whereas the intended effect of consuming a status is that nothing happens. This happens because Statuses are given CardRarity.COMMON, and ConsumeCardAction mostly checks by rarity what the resulting effect should be. 

Steps to reproduce:
1. Start a new game as Cull
2. Add a Dazed to hand
3. Add a Warcry to hand
4. Draw cards until draw pile is exactly 1 card
5. Play Warcry, put Dazed on top op draw pile
6. Add a Splinter Soul to hand
7. Play Splinter Soul

Expected result:
Dazed is consumed, giving no additional effects

Actual result:
Dazed is consumed, giving +3 maxHP

**Comment by wang429** [comment]
addressed by #323
