### ISSUE TITLE
Bad Time Eddy interactions with dex-down-at-end-of-turn and burning

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#334]
**Version**
Slay the spire: BETA
Mod version: v0.58.0

**Describe the bug**
Playing Time Eddy+:
* [x] Double-counted the dex down at end of turn effect from a temporary dex buff
* [x] Didn't trigger burning damage
* [x] Didn't trigger Transient fading

https://clips.twitch.tv/CrowdedLachrymoseShrewHoneyBadger

**Comment by wang429** [comment]
I don't have the code in front of me, but I imagine that the value of `AbstractPower::priority` for the DexDown power is higher than that of negative dex. Maybe use a TreeSet ordering the powers by priority descending before iterating through the powers?

**Comment by dbjorge** [comment]
I don't think the issue is with the priority between powers, the issue is that Time Eddy+ runs the power's atEndOfTurn callback twice without the action queue getting cleared in between; normally the actions queued as part of the powers callback would remove that power before the next turns end happens
