### ISSUE TITLE
Inferno: burning applies to more than the targetted enemy

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#335]
**Version**
Slay the spire: BETA
Mod version: v0.58.0

**Describe the bug**
Inferno applied burn to all enemies instead of just target enemy in following clip:

https://clips.twitch.tv/FlirtyInquisitivePlumberBIRB

**Comment by wang429** [comment]
I'm not seeing the issue. He remembered Lust which applies 2 burning to all enemies.

**Comment by dbjorge** [comment]
Oops, you're right; when I watched the clip the first time I saw the block number as the burning number.
