### ISSUE TITLE
Card titles should indicate Wrath metaupgrades

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#36]
It would be nice to have some sort of indicator in the card title when Wrath causes a damage increase to a card. Current proposal would be to update the card render() to look for the presence of wrath upgrades and, if present, render an overlay image that adds a wrath icon to the top-right corner and render the increase count on top of that, similar to how rendering energy cost works.

![wrath_card_title_concept](https://user-images.githubusercontent.com/376284/68361651-8192b480-00d9-11ea-8f72-fef661260a93.png)

Note that Wrath can upgrade base game colorless cards! So this will need to be implemented with `SpirePatch`es on `AbstractCard`, **not** with overrides in `CustomJorbsModCard`.

**Comment by dbjorge** [comment]
Implemented in 3fd9aa2

**Comment by Frenoss** [comment]
Maybe move the text a tiny bit to the right. What say ye?
![image](https://user-images.githubusercontent.com/6187622/68461536-48347480-01bf-11ea-9604-7333c6114fa2.png)

**Comment by dbjorge** [comment]
Yes to both

**Comment by dbjorge** [comment]
![image](https://user-images.githubusercontent.com/376284/68497006-6ecacd80-0208-11ea-8c3e-cb27abedd9a6.png)

Moved text slightly right, still need to do the portrait-view bit

**Comment by dbjorge** [comment]
![image](https://user-images.githubusercontent.com/376284/68500235-041d9000-0210-11ea-8970-3b23e8edaf73.png)

fixed as of 2dcb32a
