### ISSUE TITLE
Specific Character Run History Is Bugged

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#387]
If you want to look at past runs in the Run History for Wanderer, in the tab where you pick the specific character to look at, you have to pick CULL to look at old Wanderer runs and vice versa.

**Comment by johnplunk** [comment]
Ok, seems to be a bit different than I thought:

The Wanderer character selection only shows CULL runs.

The CULL character selection shows all runs that I have played.

**Comment by wang429** [comment]
This appears to have been fixed. Not sure when exactly. Please reopen if incorrect.
