### ISSUE TITLE
Missing Keyword Descriptions.

### ISSUE THREAD

**Issue by lobbien** [dbjorge/jorbs-spire-mod#434]
**Version**
Slay the spire: Main
Mod version: 1.4.0

Arcane Form, the Grimoire and potentially other cards with a lot of keywords don't show all keyword descriptions.

![Anmerkung 2020-02-21 173930](https://user-images.githubusercontent.com/32041265/75053273-43c36b80-54d1-11ea-9667-ca1581f91ae9.png)

^Example: Arcane form is missing keyword descriptions for "Diligence", "Chastity" and "Kindness".

**Comment by dbjorge** [comment]
Resolved in https://github.com/daviscook477/BaseMod/pull/250
