### ISSUE TITLE
Exerting a card that is not in your Master Deck causes crash to desktop

### ISSUE THREAD

**Issue by Cartopol** [dbjorge/jorbs-spire-mod#486]
**Version**
Slay the spire: MAIN
Mod version: unreleased Master branch

**Describe the bug**
When you Exert a card that is not in your Master Deck, the game crashes. This is because the SelfExertPatch tries to set ExertedField to true of the MasterDeckEquivalent of the exerted card, without checking if there is a MasterDeckEquivalent. This requires a check on != null before setting the ExertedField of a non-existing object.

**To Reproduce**
1. Enter combat as Cull
2. Create a copy of stsjorbsmod:Frustration
3. Play Frustration

**Expected behavior**
Frustration is played, moved to the exhaust pile and Exerted

**Actual behavior**
Game crashes.

**Comment by dbjorge** [comment]
Fixed in #487
