### ISSUE TITLE
Artifact should not block SnappedPower

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#52]
Probably best to add a new power type (maybe SPECIAL) as an alternative to BUFF/DEBUFF, since we'll want SnappedPower to be immune to both debuff-affecting things like artifact but also buff-affecting things like Amnesia

**Comment by wang429** [comment]
Related, current Amnesia order cleanses SnappedPower. RemoveAllPowersAction removes _all_ powers and is done after SnapAction. Either new "RemoveNonSpecialPowersAction" or patch RemoveAllPowersAction to ignore SPECIAL power types.

**Comment by dbjorge** [comment]
Yep, Amnesia will need an update. I think I'd probably lean towards making a new `RemovePowersMatchingPredicateAction` (similar to what we did for `ExhaustCardsMatchingPredicateAction`) and let `Amnesia` pass in its predicate for `p -> p.type == PowerType.BUFF || p.type == PowerType.DEBUFF`

**Comment by wang429** [comment]
Oh, Amnesia is also a curse now.

**Comment by dbjorge** [comment]
Fixed by #96
