### ISSUE TITLE
Does not have Googly Eyes. 

### ISSUE THREAD

**Issue by Nocturnhabeo** [dbjorge/jorbs-spire-mod#524]
**Version**
Slay the spire: "MAIN" 
Mod version: latest

**Additional context**
https://clips.twitch.tv/ElegantSnappyShrimpMrDestructoid

**Comment by wang429** [comment]
This is as "simple" as supporting the googly eyes mod. https://steamcommunity.com/sharedfiles/filedetails/?id=1615430126

**Comment by wang429** [comment]
oh, it's on their GitHub page https://github.com/twanvl/sts-googly-mod

**Comment by Nocturnhabeo** [comment]
Thanks that fixes it.
