### ISSUE TITLE
Mind Glass's relic outline rendering incorrectly

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#530]
[9:25 PM] Bobertg: Noticed that Mind Glass relic's outline isn't rendering properly. This is causing BaseMod's default "missing image" image to render with the relic. I did try regenerating the outline image with the script, but that didn't seem to work.

```
01:17:12.010 INFO util.TextureLoader> DefaultMod | Loading Texture: stsjorbsmodResources/images/relics/generated/MindGlassRelic_outline.png
01:17:12.010 ERROR util.TextureLoader> Could not find texture: stsjorbsmodResources/images/relics/generated/MindGlassRelic_outline.png
```

![image](https://user-images.githubusercontent.com/376284/93555353-b3081d80-f943-11ea-8cf2-a04445ac1044.png)

**Comment by NafenX** [comment]
![image](https://user-images.githubusercontent.com/28961736/97597740-146ce300-19fe-11eb-94b6-95245954dfc8.png)

So I think I fixed this just by opening the outline.jpg in GIMP, clicking Overwrite and then packaging the mod again. It made the file size go from like 500 bytes to 2.53 KB, though, so I guess it just saved with some default settings for compression etc.

I can pr this but anybody who is better with fixing graphic related bugs could take a look at it and maybe save some bytes :sweat_smile:

**Comment by acourrau** [comment]
Closing as non-reproducable in latest master (86c8b7a2)
