### ISSUE TITLE
NPE on room load when loading VOs

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#536]
wbfw109 Aug 31 @ 9:59am 
https://pastebin.com/GpHk2Jqr

In ascension 20 and Act 1 when I enter the "monster" room, sometimes the error occurs and it force to exit game.

**Comment by wang429** [comment]
Another instance https://steamcommunity.com/app/646570/workshop/

**Comment by dbjorge** [comment]
Fixed in 718e9c66
