### ISSUE TITLE
Shadow Relic

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#541]
From: https://docs.google.com/spreadsheets/d/1GY0eJsooEp361hWFL2lD-uPVa5-l-7g4f4FtyKs-k7Q/edit#gid=1067023235
Relic
Rare
Gain 1 Intangible the first time you exert a card in a combat.

**Comment by NafenX** [comment]
I had a crack at it: https://github.com/dbjorge/jorbs-spire-mod/pull/544

**Comment by acourrau** [comment]
Closing. Added with #544 being merged to master.
