### ISSUE TITLE
New Status: Burning

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#63]
Burning N: Deals N damage. Reduce N to floor(N/2). While Burning, reduce healing by 50%
Fireball+ and Firebolt+ apply burning.

**Comment by dbjorge** [comment]
Would be nice for this to use an StSLib `HealthBarRenderPower` to render the damage in the health bar like poison does

**Comment by dbjorge** [comment]
Being worked on by Bobertg in discord

**Comment by wang429** [comment]
Hey, that's me! Also, See PR #84

**Comment by wang429** [comment]
#84 merged. Closing.
