### ISSUE TITLE
"Gain clarity of current memory" effects crash when there is no current memory

### ISSUE THREAD

**Issue by OligarchButterfly** [dbjorge/jorbs-spire-mod#64]
[See log.](https://github.com/dbjorge/jorbs-spire-mod/files/3786471/SlayTheSpire_201910300108_1.log) Fighting elite sentries in act 1, went to turn 7 with Find Familiar active, and at the end of the turn the game crashes when I snap. Replaying the fight from the save, it happened again; not playing Find Familiar the third time allowed me to win without crashing after snapping.

Running on a Mac; the log looks like it has all the relevant config info.

**Comment by OligarchButterfly** [comment]
Second run, swapped boss relic because why not. Turns out that trying to gain clarity without a memory crashes the game in general (this time by playing Eye of the Storm with no starting memory).

**Comment by dbjorge** [comment]
Thanks for reporting the issue and including the log file! Will be fixed in the next release.
