### ISSUE TITLE
Mirror Image should use an StSFriendlyMinions 1hp minion instead of "next attack misses"

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#68]

**Comment by wang429** [comment]
Per Jorbs regarding attacks with a negative effect: "let's lore it that the debuffs the attacks are giving are like big aoe things, but the attack itself is single-target, and so the debuffs go to everyone even though the damage gets avoided"

If we continue down the route of using StSFriendlyMinions, this might feel inconsistent with other mod minions

**Comment by dbjorge** [comment]
Resolved by d783968
