### ISSUE TITLE
Nilary's Codex should not generate cards that grant metaupgrades

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#70]
* Anything that grants greed/gluttony/wrath
* Anything that heals you

**Comment by Frenoss** [comment]
Healing can be handled by the game by adding CardTags.HEALING.

The memories can add a new tag (PERMANENT_UPGRADE?) and patch AbstractDungeon.returnTrulyRandomCardInCombat to filter its list before returning a value.

**Comment by dbjorge** [comment]
Note that `AbstractDungeon` has several different variants that would each need to be patched similarly.

The other option would be to cheat and just use CardTags.HEALING even for the metaupgrade cases, but it would probably be preferable to use a separate tag unless the patches become really outrageous.

**Comment by Frenoss** [comment]
Adding Pride to the list of memories that should not be remembered, since it permanently upgrades a card.

**Comment by Frenoss** [comment]
Oh no. I hope I'm seeing this wrong. We want to patch the two overloads of `AbstractDungeon.returnTrulyRandomCardInCombat`. One of them has no arguments. ModTheSpire's [Patcher.java](https://github.com/kiooeht/ModTheSpire/blob/ad0120dbe12a155151e9143899e727aa51083d48/src/main/java/com/evacipated/cardcrawl/modthespire/Patcher.java) assigns a null for its 'ctParamTypes' variable when method to be patched has only the void.class parameter. When that's null at line 336, there must be only one method count.

If I'm reading this right, we can't patch the 0-argument version as it stands. Two options I see so far:
* Fork ModTheSpire and submit a pull request to handle this behavior. Use our fork until the PR is accepted.
* Patch the patcher code with our own use of Javassist before the patcher code runs. <shudder>

Thoughts? I might just submit the tagged Mending card in the meantime.

**Comment by dbjorge** [comment]
I think what you're looking for is to set `paramtypez = { }` in the SpirePatch for the nullary case. I'd bet this scenario is exactly why ModTheSpire is using `{ void.class }` instead of the more natural `{ }` as its sentinel value for `paramtypez`. I was able to get the game to patch and run with the following patch layout:

```java
    @SpirePatch(
            clz = AbstractDungeon.class,
            method = "returnTrulyRandomCardInCombat",
            paramtypez = { }
    )
    public static class AbstractDungeon_returnTrulyRandomCardInCombat_1 {
        @SpirePrefixPatch
        public static void patch() {
            JorbsMod.logger.info("in returnTrulyRandomCardInCombat() patch");
        }
    }

    @SpirePatch(
            clz = AbstractDungeon.class,
            method = "returnTrulyRandomCardInCombat",
            paramtypez = { CardType.class }
    )
    public static class AbstractDungeon_returnTrulyRandomCardInCombat_2 {
        @SpirePrefixPatch
        public static void patch(CardType cardType) {
            JorbsMod.logger.info("in returnTrulyRandomCardInCombat(CardType cardType) patch");
        }
    }
```

**Comment by Frenoss** [comment]
Thanks, the empty list is exactly what I was looking for.
