### ISSUE TITLE
Animate Objects should be eligible for Wrath upgrades

### ISSUE THREAD

**Issue by dbjorge** [dbjorge/jorbs-spire-mod#73]
Currently it's not because it has a baseDamage of 0. Might have to special case it.

**Comment by dbjorge** [comment]
* need clarification whether it should add a flat 1 vs 1 per applicable card

**Comment by Frenoss** [comment]
Because of the sheet's request to make the damage repeat per card, to trigger on-hit effects, I'm going to interpret it as "Wrath bonus per card".

**Comment by dbjorge** [comment]
Yes, it should work like other multihit effects; wrath should apply to baseDamage as normal for each hit
