### ISSUE TITLE
Wish changes enemy types when used

### ISSUE THREAD

**Issue by johnplunk** [dbjorge/jorbs-spire-mod#98]
EX: Wish used on Act 3 shapes/spheric guardian fight changed an exploder into a spiker

**Comment by dbjorge** [comment]
This is a good example of the sort of "exciting" edge cases to the wish effect that are hard to get right; we discussed in discord that we probably want to redesign the wish card effect, but there isn't a new idea in the spreadsheet yet.

Should probably hold off on trying to pick up this bug until we decide if we're redesigning the whole card mechanic

**Comment by dbjorge** [comment]
Confirmed that we're just going to be getting rid of wish entirely, so closing this issue as obsolete
